#尚未成功配置重试，配置httpclient超时结果会直接返回，不会重试
spring:
  application:
    name: gateway9528
  cloud:
    gateway:
      httpclient:
        connect-timeout: 250 #gateway转发后链接超时时间
        response-timeout: 1000 #响应时间
      routes:
      - id: route1
        uri: lb://springtest-dept # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
        predicates:
#        匹配指定的路径，进行转发
        - Path=/dept/**
#        在某个时间之前的请求才会被转发到 http://localhost:8001,
#        - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#        在某个时间之后的请求才会被转发
#        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#        在某个时间段之间的才会被转发
#        - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#        名为chocolate的表单或者满足正则ch.p的表单才会被匹配到进行请求转发
#        - Cookie=chocolate, ch.p
#        携带参数X-Request-Id或者满足\d+的请求头才会匹配
#        - Header=X-Request-Id, \d+
#        指定host，制定后不能再使用localhost或ip等方式访问
#        - Host=qiying.com:8080
#        只有GET方法才会匹配
#        - Method=GET
        filters:
        #注意各过滤器有先后顺序
#        - StripPrefix=1 #转发后的路径截取第级地址，0为不截取
#        - PrefixPath=/dept #转发后的路径前缀
#        - RewritePath=/dept/rewrite, /dept #重写转发路径。访问localhost:9526/dept/rewrite/**, 请求会转发到springtest-dept/**
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallbackuri #hystrix触发后，访问本项目的controller
        - name: Retry
          args:
            retries: 3 #重试次数，默认值是3次
            series:
              #状态码配置（分段），符合的某段状态码才会进行重试逻辑，默认值是SERVER_ERROR，值是5，也就是5XX(5开头的状态码)，共有5个值。
            - INFORMATIONAL #1
#            - SUCCESSFUL #2
            - REDIRECTION #3
            - CLIENT_ERROR #4
            - SERVER_ERROR #5
            statuses:
            - GATEWAY_TIMEOUT
            - BAD_GATEWAY
#            methods: #指定哪些方法的请求需要进行重试逻辑，默认值是GET方法。GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE;
#            - GET
#            - POST
#gateway的重试暂不支持带有body的请求，如post\put等
server:
  port: 9528
eureka:
  client:
    service-url:
      defaultZone: http://etest:123@eureka7001.com:7001/eureka/,http://etest:123@eureka7002.com:7002/eureka/,http://etest:123@eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
