spring:
  application.name: service-turbine
server:
  port: 9102
turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问，如8001,8002hystrix两个节点配置了S8001,S8002，此处可写为S8001,S8002
  appConfig: springtest-dept  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: new String("default") 时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 3. 当clusterNameExpression: metadata['cluster'] 时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC
  combine-host-port: true
  #更改turbine连接的默认uri ,默认为/actuator/hystrix.stream。与registrationBean.addUrlMappings("/hystrix.stream");中相同
  instanceUrlSuffix: /hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://etest:123@eureka7001.com:7001/eureka/,http://etest:123@eureka7002.com:7002/eureka/