server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://etest:123@eureka7001.com:7001/eureka/,http://etest:123@eureka7002.com:7002/eureka/,http://etest:123@eureka7003.com:7003/eureka/
feign:
  hystrix:
    enabled: true # 不添加此配置，fallbackMethod不会生效
#当启用ribbon时，配置ribbon重试即配置feign重试
ribbon:
  #配置首台服务器重试
  MaxAutoRetries: 0
  #配置其他服务器重试
  MaxAutoRetriesNextServer: 5
  #链接超时时间
  ConnectTimeout: 250
  #请求处理时间
  ReadTimeout: 1000
  #每个操作都开启重试机制
  OkToRetryOnAllOperations: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #需要让 断路器的超时时间 大于 重试总时间
